# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: realestate/v1/realestate.proto for package 'realestate.v1'

require 'grpc'
require 'realestate/v1/realestate_pb'

module Realestate
  module V1
    module Valuation
      # ── Valuation (the "Brain") ──────────────────────────────────────────────────
      #
      # Valuation produces a real-time, source-cited home valuation.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'realestate.v1.Valuation'

        rpc :GetValuation, ::Realestate::V1::GetValuationRequest, ::Realestate::V1::GetValuationResponse
      end

      Stub = Service.rpc_stub_class
    end
    module Verification
      # ── Verification (the "Lawyer") ──────────────────────────────────────────────
      #
      # Verification checks customer-facing claims against source data before send.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'realestate.v1.Verification'

        rpc :VerifyMessage, ::Realestate::V1::VerifyMessageRequest, ::Realestate::V1::VerifyMessageResponse
      end

      Stub = Service.rpc_stub_class
    end
    module Domain
      # ── Domain (the transaction/CRM core, served by Rails) ───────────────────────
      #
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'realestate.v1.Domain'

        rpc :CreateLead, ::Realestate::V1::CreateLeadRequest, ::Realestate::V1::Lead
        rpc :EnqueueHandoff, ::Realestate::V1::HandoffPacket, ::Realestate::V1::EnqueueHandoffResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
