# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from genproto.realestate.v1 import realestate_pb2 as realestate_dot_v1_dot_realestate__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in realestate/v1/realestate_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ValuationStub(object):
    """── Valuation (the "Brain") ──────────────────────────────────────────────────

    Valuation produces a real-time, source-cited home valuation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetValuation = channel.unary_unary(
                '/realestate.v1.Valuation/GetValuation',
                request_serializer=realestate_dot_v1_dot_realestate__pb2.GetValuationRequest.SerializeToString,
                response_deserializer=realestate_dot_v1_dot_realestate__pb2.GetValuationResponse.FromString,
                _registered_method=True)


class ValuationServicer(object):
    """── Valuation (the "Brain") ──────────────────────────────────────────────────

    Valuation produces a real-time, source-cited home valuation.
    """

    def GetValuation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValuationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetValuation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValuation,
                    request_deserializer=realestate_dot_v1_dot_realestate__pb2.GetValuationRequest.FromString,
                    response_serializer=realestate_dot_v1_dot_realestate__pb2.GetValuationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'realestate.v1.Valuation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('realestate.v1.Valuation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Valuation(object):
    """── Valuation (the "Brain") ──────────────────────────────────────────────────

    Valuation produces a real-time, source-cited home valuation.
    """

    @staticmethod
    def GetValuation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.v1.Valuation/GetValuation',
            realestate_dot_v1_dot_realestate__pb2.GetValuationRequest.SerializeToString,
            realestate_dot_v1_dot_realestate__pb2.GetValuationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VerificationStub(object):
    """── Verification (the "Lawyer") ──────────────────────────────────────────────

    Verification checks customer-facing claims against source data before send.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyMessage = channel.unary_unary(
                '/realestate.v1.Verification/VerifyMessage',
                request_serializer=realestate_dot_v1_dot_realestate__pb2.VerifyMessageRequest.SerializeToString,
                response_deserializer=realestate_dot_v1_dot_realestate__pb2.VerifyMessageResponse.FromString,
                _registered_method=True)


class VerificationServicer(object):
    """── Verification (the "Lawyer") ──────────────────────────────────────────────

    Verification checks customer-facing claims against source data before send.
    """

    def VerifyMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VerificationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyMessage,
                    request_deserializer=realestate_dot_v1_dot_realestate__pb2.VerifyMessageRequest.FromString,
                    response_serializer=realestate_dot_v1_dot_realestate__pb2.VerifyMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'realestate.v1.Verification', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('realestate.v1.Verification', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Verification(object):
    """── Verification (the "Lawyer") ──────────────────────────────────────────────

    Verification checks customer-facing claims against source data before send.
    """

    @staticmethod
    def VerifyMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.v1.Verification/VerifyMessage',
            realestate_dot_v1_dot_realestate__pb2.VerifyMessageRequest.SerializeToString,
            realestate_dot_v1_dot_realestate__pb2.VerifyMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConversationStub(object):
    """── Conversation (the agent loop: generate→critique→fair-housing→decide) ─────

    Conversation runs one turn of the LangGraph orchestrator end to end and
    returns the full reasoning trace (draft, per-claim verdicts, citations,
    confidence sub-signals, Fair Housing decision, handoff trigger) so a UI can
    SHOW the agent reasoning over live data, not just the final answer.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Orchestrate = channel.unary_unary(
                '/realestate.v1.Conversation/Orchestrate',
                request_serializer=realestate_dot_v1_dot_realestate__pb2.OrchestrateRequest.SerializeToString,
                response_deserializer=realestate_dot_v1_dot_realestate__pb2.OrchestrateResponse.FromString,
                _registered_method=True)


class ConversationServicer(object):
    """── Conversation (the agent loop: generate→critique→fair-housing→decide) ─────

    Conversation runs one turn of the LangGraph orchestrator end to end and
    returns the full reasoning trace (draft, per-claim verdicts, citations,
    confidence sub-signals, Fair Housing decision, handoff trigger) so a UI can
    SHOW the agent reasoning over live data, not just the final answer.
    """

    def Orchestrate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Orchestrate': grpc.unary_unary_rpc_method_handler(
                    servicer.Orchestrate,
                    request_deserializer=realestate_dot_v1_dot_realestate__pb2.OrchestrateRequest.FromString,
                    response_serializer=realestate_dot_v1_dot_realestate__pb2.OrchestrateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'realestate.v1.Conversation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('realestate.v1.Conversation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Conversation(object):
    """── Conversation (the agent loop: generate→critique→fair-housing→decide) ─────

    Conversation runs one turn of the LangGraph orchestrator end to end and
    returns the full reasoning trace (draft, per-claim verdicts, citations,
    confidence sub-signals, Fair Housing decision, handoff trigger) so a UI can
    SHOW the agent reasoning over live data, not just the final answer.
    """

    @staticmethod
    def Orchestrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.v1.Conversation/Orchestrate',
            realestate_dot_v1_dot_realestate__pb2.OrchestrateRequest.SerializeToString,
            realestate_dot_v1_dot_realestate__pb2.OrchestrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DomainStub(object):
    """── Domain (the transaction/CRM core, served by Rails) ───────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLead = channel.unary_unary(
                '/realestate.v1.Domain/CreateLead',
                request_serializer=realestate_dot_v1_dot_realestate__pb2.CreateLeadRequest.SerializeToString,
                response_deserializer=realestate_dot_v1_dot_realestate__pb2.Lead.FromString,
                _registered_method=True)
        self.EnqueueHandoff = channel.unary_unary(
                '/realestate.v1.Domain/EnqueueHandoff',
                request_serializer=realestate_dot_v1_dot_realestate__pb2.HandoffPacket.SerializeToString,
                response_deserializer=realestate_dot_v1_dot_realestate__pb2.EnqueueHandoffResponse.FromString,
                _registered_method=True)
        self.CreateOffer = channel.unary_unary(
                '/realestate.v1.Domain/CreateOffer',
                request_serializer=realestate_dot_v1_dot_realestate__pb2.CreateOfferRequest.SerializeToString,
                response_deserializer=realestate_dot_v1_dot_realestate__pb2.Offer.FromString,
                _registered_method=True)


class DomainServicer(object):
    """── Domain (the transaction/CRM core, served by Rails) ───────────────────────

    """

    def CreateLead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueHandoff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOffer(self, request, context):
        """CreateOffer lands a drafted cash/purchase offer in the broker-sign queue
        (status awaiting_broker). A licensed human broker reviews and signs; the
        agent never signs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DomainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateLead': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLead,
                    request_deserializer=realestate_dot_v1_dot_realestate__pb2.CreateLeadRequest.FromString,
                    response_serializer=realestate_dot_v1_dot_realestate__pb2.Lead.SerializeToString,
            ),
            'EnqueueHandoff': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueHandoff,
                    request_deserializer=realestate_dot_v1_dot_realestate__pb2.HandoffPacket.FromString,
                    response_serializer=realestate_dot_v1_dot_realestate__pb2.EnqueueHandoffResponse.SerializeToString,
            ),
            'CreateOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOffer,
                    request_deserializer=realestate_dot_v1_dot_realestate__pb2.CreateOfferRequest.FromString,
                    response_serializer=realestate_dot_v1_dot_realestate__pb2.Offer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'realestate.v1.Domain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('realestate.v1.Domain', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Domain(object):
    """── Domain (the transaction/CRM core, served by Rails) ───────────────────────

    """

    @staticmethod
    def CreateLead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.v1.Domain/CreateLead',
            realestate_dot_v1_dot_realestate__pb2.CreateLeadRequest.SerializeToString,
            realestate_dot_v1_dot_realestate__pb2.Lead.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueHandoff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.v1.Domain/EnqueueHandoff',
            realestate_dot_v1_dot_realestate__pb2.HandoffPacket.SerializeToString,
            realestate_dot_v1_dot_realestate__pb2.EnqueueHandoffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.v1.Domain/CreateOffer',
            realestate_dot_v1_dot_realestate__pb2.CreateOfferRequest.SerializeToString,
            realestate_dot_v1_dot_realestate__pb2.Offer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
